version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #restart: unless-stopped
    env_file: docker.env
    security_opt:
      - no-new-privileges:true
    volumes:
      - diarios:/usr/src/app/diarios
      - /etc/localtime:/etc/localtime:ro
volumes:
  diarios:
