version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: docker.env
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./diarios:/usr/src/app/diarios
      - /etc/localtime:/etc/localtime:ro
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    networks:
      - nginx-docker_interna
    #ports:
    #  - "8095:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./public:/usr/local/apache2/htdocs/

networks:
  nginx-docker_interna:
    external: true
