version: '2.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TESTING=${TESTING}
      - LOG_FOLDER=${LOG_FOLDER}
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./diarios:/usr/src/app/diarios
      - /etc/localtime:/etc/localtime:ro
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - REACT_APP_COUNTRY=${REACT_APP_COUNTRY}
      - REACT_APP_MEDIOS=${REACT_APP_MEDIOS}
      - REACT_APP_MEDIOS_BD_NAMES=${REACT_APP_MEDIOS_BD_NAMES}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    command: ./node_modules/serve/bin/serve.js -s build
    entrypoint: /docker-entrypoint-web.sh
    ports:
      - "127.0.0.1:8090:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: node server.js
    entrypoint: /docker-entrypoint.sh
    ports:
      - "127.0.0.1:8095:8000"
    volumes:
      - ./nodemodules:/usr/src/app/node_modules
      - ./diarios:/usr/src/app/diarios:ro
      - /etc/localtime:/etc/localtime:ro
