FROM node:13
MAINTAINER Lu Pa <admin@tedic.org>

ENV DEBIAN_FRONTEND noninteractive
ENV CODE https://github.com/samsaurio/ConsultasAPI.git

RUN apt-get update \
        && apt-get install -y \
                git \
        && apt-get clean

WORKDIR /usr/src/app

RUN git clone $CODE .

COPY docker-entrypoint.sh /

